Repository Black-Dot-2024/Zeitgeist-Backend, pull requests merged in 2024-04, with the labels that each got.

#19 chore(Project): removed OOP approach
  src/api/controllers/dummy.controller.ts
  src/api/routes/dummy.routes.ts
  src/api/routes/index.routes.ts
  src/core/app/services/dummy.services.ts
  src/core/errors/core/base-error.error.ts
  src/core/errors/not-found.error.ts
  src/core/infra/repositories/__tests__/dummyRepository.spec.ts
  src/core/infra/repositories/dummy.respository.ts
  src/index.ts
Labels: Zeitgeist

#41 chore(packageJSON): added respective chai version that works with typ…
  package.json
  pnpm-lock.yaml
Labels: bug, enhancement

#37 RF47: Iniciar sesion
  .github/workflows/develop.yml
  package.json
  pnpm-lock.yaml
  prisma/migrations/20240413034351_delete_phone_number_employee/migration.sql
  prisma/migrations/20240414012922_update_rol_default/migration.sql
  prisma/migrations/20240414014528_achived_is_back/migration.sql
  prisma/migrations/20240414190412_area_in_project/migration.sql
  prisma/schema.prisma
  src/api/controllers/employee.controller.ts
  src/api/middlewares/auth.middleware.ts
  src/api/routes/employee.routes.ts
  src/api/routes/index.routes.ts
  src/config/firebase-admin.config.ts
  src/core/app/services/__tests__/employee.service.test.ts
  src/core/app/services/employee.service.ts
  src/core/domain/entities/employee.entity.ts
  src/core/errors/core/error-code.enum.ts
  src/core/errors/unauthorize.error.ts
  src/core/infra/mappers/company-entity-from-db-model-mapper.ts
  src/core/infra/mappers/employee-entity-from-db-model.mapper.ts
  src/core/infra/mappers/project-entity-from-db-model-mapper.ts
  src/core/infra/mappers/role-entity-from-db-model.mapper.ts
  src/core/infra/repositories/employee.repository.ts
  src/utils/constants.ts
  src/utils/enums/index.ts
Labels: enhancement

#49 RF51: Find all employees
  src/api/controllers/employee.controller.ts
  src/api/routes/employee.routes.ts
  src/core/app/services/__tests__/employee.service.test.ts
  src/core/app/services/employee.service.ts
  src/core/infra/repositories/employee.repository.ts
Labels: enhancement

#35 Modificar rol usuario
  .gitignore
  src/api/controllers/admin.controller.ts
  src/api/routes/admin.routes.ts
  src/api/routes/index.routes.ts
  src/core/app/services/admin-role.services.ts
  src/core/domain/entities/employee.entity.ts
  src/core/infra/repositories/employee.repository.ts
Labels: Zeitgeist

#45 Feat/rf27 consultar clientes
  .env.example
  .eslintrc.js
  .github/workflows/develop.yml
  .husky/commit-msg
  Doxyfile
  LICENSE
  package.json
  pnpm-lock.yaml
  prisma/migrations/20240412044603_archived/migration.sql
  prisma/migrations/20240412051206_archived/migration.sql
  prisma/migrations/20240417043055_init/migration.sql
  prisma/schema.prisma
  src/api/controllers/company.controller.ts
  src/api/controllers/employee.controller.ts
  src/api/middlewares/auth.middleware.ts
  src/api/routes/company.routes.ts
  src/api/routes/index.routes.ts
  src/api/routes/project.routes.ts
  src/core/app/interfaces/dummy.interface.ts
  src/core/app/interfaces/project-report.interface.ts
  src/core/app/services/__tests__/company.service.test.ts
  src/core/app/services/__tests__/dummy.service.test.ts
  src/core/app/services/__tests__/employee.service.test.ts
  src/core/app/services/__tests__/project.service.test.ts
  src/core/app/services/company.services.ts
  src/core/app/services/employee.services.ts
  src/core/app/services/project-report.services.ts
  src/core/domain/entities/company.entity.ts
  src/core/domain/entities/employee-task.entity.ts
  src/core/domain/entities/project.entity.ts
  src/core/domain/entities/task.entity.ts
  src/core/infra/mappers/company-entity-from-db-model-mapper.ts
  src/core/infra/mappers/company-entity-from-db-model.mapper.ts
  src/core/infra/mappers/project-entity-from-db-model-mapper.ts
  src/core/infra/mappers/project-entity-from-db-model.mapper.ts
  src/core/infra/repositories/company.repository.ts
  src/core/infra/repositories/employee-task.repository.ts
  src/core/infra/repositories/project.repository.ts
  src/core/infra/repositories/tasks.repository.ts
  src/index.ts
  src/utils/constants.ts
Labels: enhancement, Zeitgeist

#39 Feat/rf25 create task
  .gitignore
  .mocharc.json
  db/find_project_db.sql
  package.json
  pnpm-lock.yaml
  src/api/controllers/task.controller.ts
  src/api/routes/index.routes.ts
  src/api/routes/task.routes.ts
  src/core/app/services/__tests__/task.services.test.ts
  src/core/app/services/project-report.services.ts
  src/core/app/services/task.services.ts
  src/core/domain/entities/task.entity.ts
  src/core/infra/repositories/tasks.repository.ts
  src/utils/enums/index.ts
Labels: enhancement

#110 refactor/RF25 - Create task
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  src/api/controllers/task.controller.ts
  src/api/routes/task.routes.ts
  src/core/app/services/__tests__/task.services.test.ts
  src/core/app/services/task.service.ts
  src/core/domain/entities/task.entity.ts
  src/core/infra/mappers/task-entity-from-db-model-mapper.ts
  src/core/infra/repositories/employee-task.repository.ts
  src/core/infra/repositories/tasks.repository.ts
Labels: enhancement

#52 Feat/rf19 crear cliente
  .gitignore
  pnpm-lock.yaml
  prisma/migrations/20240418185828_update_company/migration.sql
  prisma/migrations/20240426063110_init/migration.sql
  prisma/migrations/20240426063222_company_update/migration.sql
  prisma/schema.prisma
  src/api/controllers/company.controller.ts
  src/api/middlewares/auth.middleware.ts
  src/api/middlewares/rbac.middleware.ts
  src/api/routes/company.routes.ts
  src/api/routes/project.routes.ts
  src/api/validation/companyValidation.ts
  src/core/app/services/__tests__/company.service.test.ts
  src/core/app/services/company.service.ts
  src/core/app/services/employee.service.ts
  src/core/app/services/project-report.service.ts
  src/core/domain/entities/company.entity.ts
  src/core/domain/entities/employee-notification.entity.ts
  src/core/domain/entities/employee-task.entity.ts
  src/core/domain/entities/employee.entity.ts
  src/core/domain/entities/project.entity.ts
  src/core/domain/entities/task.entity.ts
  src/core/infra/mappers/company-entity-from-db-model.mapper.ts
  src/core/infra/repositories/company.repository.ts
Labels: Zeitgeist

#129 Refactor/rf25 create task
  src/api/controllers/task.controller.ts
  src/api/routes/employee.routes.ts
  src/core/infra/repositories/tasks.repository.ts
Labels: enhancement, Zeitgeist
