Repository Black-Dot-2024/Zeitgeist-Backend, pull requests merged in 2024-05, with the labels that each got.

#92 [Feature/RF18]: Modificar información del cliente
  package.json
  pnpm-lock.yaml
  src/api/controllers/company.controller.ts
  src/api/routes/company.routes.ts
  src/api/validators/company.validator.ts
  src/api/validators/zod.validator.ts
  src/core/app/interfaces/company.interface.ts
  src/core/app/services/__tests__/company.service.test.ts
  src/core/app/services/company.service.ts
  src/core/domain/entities/company.entity.ts
  src/core/infra/repositories/company.repository.ts
Labels: enhancement

#139 feat/RF02-assignedTasks
  src/api/controllers/task.controller.ts
  src/api/routes/project.routes.ts
  src/api/routes/task.routes.ts
  src/core/app/services/__tests__/task.services.test.ts
  src/core/app/services/project.service.ts
  src/core/app/services/task.service.ts
  src/core/infra/repositories/employee-task.repository.ts
  src/core/infra/repositories/tasks.repository.ts
Labels: enhancement, Zeitgeist

#140 feat/RF26-delete-task
  src/api/controllers/task.controller.ts
  src/api/routes/task.routes.ts
  src/core/app/services/__tests__/task.services.test.ts
  src/core/app/services/task.service.ts
  src/core/infra/repositories/tasks.repository.ts
Labels: enhancement, Zeitgeist

#143 Feat/rf 15 edit project
  src/api/controllers/project.controller.ts
  src/api/routes/project.routes.ts
  src/core/app/interfaces/project.interface.ts
  src/core/app/services/__tests__/project.service.test.ts
  src/core/app/services/project.service.ts
  src/core/infra/repositories/project.repository.ts
Labels: Zeitgeist

#156 fix(projects): order projects by status
  src/core/infra/repositories/project.repository.ts
Labels: enhancement

#161 refactor(routes): Updated routes orderings
  src/api/routes/admin.routes.ts
  src/api/routes/company.routes.ts
  src/api/routes/employee.routes.ts
  src/api/routes/notification.routes.ts
  src/api/routes/project.routes.ts
  src/api/routes/task.routes.ts
Labels: enhancement, Zeitgeist

#176 fix(createTask): new endpoint for create task
  src/api/routes/employee.routes.ts
Labels: bug, Zeitgeist

#169 Fix/projects
  src/api/controllers/project.controller.ts
  src/core/app/services/__tests__/company.service.test.ts
  src/core/app/services/__tests__/home.service.test.ts
  src/core/app/services/__tests__/project.service.test.ts
  src/core/app/services/home.service.ts
  src/core/app/services/project.service.ts
  src/core/infra/repositories/project.repository.ts
Labels: bug

#183 fix(assignDepartment): now assigns department without destroying the DB
  src/api/controllers/admin.controller.ts
  src/api/controllers/department.controller.ts
  src/api/routes/department.routes.ts
  src/api/routes/index.routes.ts
  src/core/app/services/admin-role.service.ts
  src/core/app/services/department.service.ts
  src/core/infra/repositories/department.repository.ts
Labels: enhancement, Zeitgeist

#191 Fix/Validators according to db
  prisma/migrations/20240516211029_fix_employee_task_on_delete_cascade/migration.sql
  prisma/schema.prisma
  src/api/controllers/employee.controller.ts
  src/api/controllers/task.controller.ts
  src/api/validators/company.validator.ts
  src/api/validators/zod.validator.ts
Labels: enhancement, Zeitgeist

#195 Feat/task employee project
  src/core/app/services/__tests__/task.services.test.ts
  src/core/app/services/task.service.ts
  src/core/domain/entities/task.entity.ts
  src/core/infra/repositories/employee-task.repository.ts
Labels: Zeitgeist

#205 Feat/Expenses/RF32: Endpoint for expenseReport data by id
  prisma/migrations/20240522045959_expenses_update_fields/migration.sql
  prisma/schema.prisma
  src/api/controllers/expense.controller.ts
  src/api/routes/expense.routes.ts
  src/api/routes/index.routes.ts
  src/core/app/services/__tests__/expense.service.test.ts
  src/core/app/services/expense.service.ts
  src/core/domain/entities/expense.entity.ts
  src/core/infra/mappers/expense-entity-from-db-model.mapper.ts
  src/core/infra/repositories/expense.repository.ts
  src/utils/enums/index.ts
Labels: enhancement, Zeitgeist

#220 Feat/Expenses/RF32: Endpoint for expenseReport data by id
  prisma/schema.prisma
  src/api/controllers/expense.controller.ts
  src/api/routes/expense.routes.ts
  src/api/routes/index.routes.ts
  src/core/app/services/__tests__/expense.service.test.ts
  src/core/app/services/expense.service.ts
  src/core/domain/entities/expense.entity.ts
  src/core/infra/mappers/expense-entity-from-db-model.mapper.ts
  src/core/infra/repositories/expense.repository.ts
  src/utils/enums/index.ts
Labels: enhancement

#224 fix(RF32): Add accounting role to access all expense reports
  src/core/app/services/expense.service.ts
Labels: enhancement

#225 Fix/tasks date
  src/core/app/services/__tests__/task.services.test.ts
  src/core/app/services/task.service.ts
  src/utils/methods.ts
Labels: bug

#233 feat/RF40 modificar estatus viatico
  src/api/controllers/expense.controller.ts
  src/api/routes/expense.routes.ts
  src/core/app/services/__tests__/company.service.test.ts
  src/core/app/services/__tests__/expense.service.test.ts
  src/core/app/services/__tests__/task.services.test.ts
  src/core/app/services/expense.service.ts
  src/core/infra/repositories/expense.repository.ts
Labels: enhancement
